@startuml
    class Restaurant {
        - id: Integer
        - name: String
        - menus: Array<Menu>
        - reviews: Array<Review>
        --Setters--
        + addMenu(<Menu>)
        + removeMenu(<Menu>)
        + setName(name)
        + addReview(review)
        + removeReview(id)
        --Getters--
        + getId()
        + getName()
        + getMenus()
        + getReviews()
    }

    class Menu{
        - id: Integer
        - title: String
        - icon: String
        - items: Array<Items>
        --Setters--
        + addItem(<Item>)
        + removeItem(<Item>)
        + setIcon(url)
        + setTitle(title)
        --Getters--
        + getId()
        + getTitle()
        + getIcon()
        + getItems()
    }

    class Item {
        - id: Integer
        - name: String
        - icon: String
        - cost: float
        --Setters--
        + setName(name)
        + setCost(cost)
        --Getters--
        + getId()
        + getName()
        + getCost()
    }

    class Review {
        - id: Integer
        - author: String
        - rating: Integer
        - desription: String
        ---
        checkRating(rating)
        --Setters--
        + setAuthor(name)
        + setRating(rating)
        + setDescription(description)
        --Getters--
        + getId()
        + getAuthor()
        + getRating()
        + getDescription()

    }

    Restaurant --{ Menu
    Restaurant --{ Review
    Menu --{ Item
@enduml